In [1]:
import torch

In [2]:
print(torch.cuda.is_available())

True


Refer https://www.learnpytorch.io for further concepts on PyTorch

In [3]:
print(torch.__version__)

2.2.1+cu121


In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt #install pyarrow

## Tensors

In [7]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [11]:
vector = torch.tensor([1, 10])
vector

tensor([ 1, 10])

In [12]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [20]:
MATRIX = torch.tensor([[7, 9],
                      [4, 10]])

MATRIX

tensor([[ 7,  9],
        [ 4, 10]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX[0]

tensor([7, 9])

In [28]:
TENSOR = torch.tensor([[[11, 20, 4],
                       [4, 5, 5],
                      [3, 9, 4]]])
TENSOR

tensor([[[11, 20,  4],
         [ 4,  5,  5],
         [ 3,  9,  4]]])

In [29]:
TENSOR.ndim

3

In [34]:
TENSOR[0, 1]

tensor([4, 5, 5])

In [33]:
TENSOR.shape

torch.Size([1, 3, 3])

In [36]:
TENSOR.size()

torch.Size([1, 3, 3])

### Random Tensors