In [2]:
import torch

In [3]:
print(torch.cuda.is_available())

True


Refer https://www.learnpytorch.io for further concepts on PyTorch

In [4]:
print(torch.__version__)

2.2.1+cu121


In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt #install pyarrow

## Tensors

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
vector = torch.tensor([1, 10])
vector

tensor([ 1, 10])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
MATRIX = torch.tensor([[7, 9],
                      [4, 10]])

MATRIX

tensor([[ 7,  9],
        [ 4, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 9])

In [15]:
TENSOR = torch.tensor([[[11, 20, 4],
                       [4, 5, 5],
                      [3, 9, 4]]])
TENSOR

tensor([[[11, 20,  4],
         [ 4,  5,  5],
         [ 3,  9,  4]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR[0, 1]

tensor([4, 5, 5])

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR.size()

torch.Size([1, 3, 3])

### Random Tensors

In [20]:
rand_tensor = torch.rand(2,2)
print(rand_tensor)

tensor([[0.5060, 0.5290],
        [0.4037, 0.8997]])


In [21]:
rand_tensor.shape, rand_tensor.ndim


(torch.Size([2, 2]), 2)

A **tensor** is both a container for numbers as well as set of rules that define transformations between tensors that produce new tensors. (Multidimensional Arrays)

Every tensor has a **rank** that corresponds to its dimensional space.

In [22]:
tensor = torch.tensor([[0,0,1], [0,1,0], [1,0,0]])
tensor

tensor([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])

In [23]:
x[0][0] = 5
x

NameError: name 'x' is not defined

In [ ]:
x[0][1] = 10
x

In [ ]:
x[1][2] = 20
x

In [ ]:
zeros=torch.zeros(2,2)
zeros

In [ ]:
ones = torch.ones(2,2)
ones

In [ ]:
add = torch.ones(1,2) + torch.ones(1,2)

add

In [ ]:
r1=torch.rand(1).item()
r1

### CPU Tensor to GPU Tensor

In [ ]:
CPU_tensor = torch.rand(2,2)
CPU_tensor.device

In [ ]:
GPU_tensor = CPU_tensor.to("cuda")
GPU_tensor.device

### Max

In [ ]:
torch.rand(2,2).max()

In [24]:
torch.rand(2,2).max().item()

0.9650959968566895

In [25]:
long_tensor = torch.tensor([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
long_tensor

tensor([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])

In [26]:
long_tensor.type()

'torch.LongTensor'

In [27]:
float_tensor = torch.tensor([[0,0,1], [1, 1, 1], [10, 0, 10]]).to(dtype=torch.float32)
float_tensor,float_tensor.type()


(tensor([[ 0.,  0.,  1.],
         [ 1.,  1.,  1.],
         [10.,  0., 10.]]),
 'torch.FloatTensor')

In [28]:
float_tensor2 = torch.tensor([[0.2, 0.1, 0.5], [3.5, 3.4, 2.3], [1.3, 2.3, 5.5]])
float_tensor2, float_tensor2.type()

(tensor([[0.2000, 0.1000, 0.5000],
         [3.5000, 3.4000, 2.3000],
         [1.3000, 2.3000, 5.5000]]),
 'torch.FloatTensor')

In-Place Function (Most of the functions create a new tensor to store its values, using _ after the name of the function calls the in-place function which manipulates upon the existing tensor.)

In [29]:
rand_tensor = torch.tensor([2, 4, 8, 16]).to(dtype=torch.float32) #log2 
rand_tensor

tensor([ 2.,  4.,  8., 16.])

In [30]:
rand_tensor.log2_()

tensor([1., 2., 3., 4.])

### Reshaping a tensor

In [31]:
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1, 28, 28) # 28x28=784
viewed_tensor, viewed_tensor.shape

(tensor([[[7.7843e-01, 2.1256e-02, 1.6252e-01, 7.9723e-02, 6.5601e-01,
           1.2435e-01, 7.2762e-01, 8.2187e-01, 9.8301e-01, 6.5707e-01,
           7.4469e-01, 3.6344e-01, 2.5676e-02, 8.3301e-01, 9.0855e-01,
           3.3972e-01, 3.8007e-01, 8.0824e-01, 4.6945e-01, 3.1566e-01,
           6.2335e-01, 6.6916e-01, 6.1811e-01, 1.8624e-01, 4.7521e-01,
           8.8554e-01, 1.0914e-01, 7.1212e-01],
          [8.2939e-01, 7.9569e-01, 7.9299e-01, 9.1295e-02, 3.7733e-01,
           9.6098e-01, 4.0625e-01, 4.7255e-01, 8.3050e-02, 2.0135e-02,
           8.1866e-01, 3.0328e-01, 2.3282e-01, 1.5684e-01, 1.3438e-01,
           1.7451e-01, 3.9390e-01, 2.4311e-02, 2.8947e-01, 6.1742e-02,
           6.7067e-01, 1.5386e-01, 3.4892e-01, 6.3688e-02, 1.2364e-02,
           1.3409e-01, 5.2426e-01, 6.1800e-01],
          [6.1178e-01, 5.9954e-02, 7.2699e-01, 6.9986e-02, 4.6896e-02,
           2.7759e-01, 9.5121e-01, 4.8335e-01, 9.2043e-02, 7.8694e-01,
           7.3940e-01, 5.2343e-01, 4.1863e-01, 4.999

In [32]:
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
reshaped_tensor, reshaped_tensor.shape

(tensor([[[7.7843e-01, 2.1256e-02, 1.6252e-01, 7.9723e-02, 6.5601e-01,
           1.2435e-01, 7.2762e-01, 8.2187e-01, 9.8301e-01, 6.5707e-01,
           7.4469e-01, 3.6344e-01, 2.5676e-02, 8.3301e-01, 9.0855e-01,
           3.3972e-01, 3.8007e-01, 8.0824e-01, 4.6945e-01, 3.1566e-01,
           6.2335e-01, 6.6916e-01, 6.1811e-01, 1.8624e-01, 4.7521e-01,
           8.8554e-01, 1.0914e-01, 7.1212e-01],
          [8.2939e-01, 7.9569e-01, 7.9299e-01, 9.1295e-02, 3.7733e-01,
           9.6098e-01, 4.0625e-01, 4.7255e-01, 8.3050e-02, 2.0135e-02,
           8.1866e-01, 3.0328e-01, 2.3282e-01, 1.5684e-01, 1.3438e-01,
           1.7451e-01, 3.9390e-01, 2.4311e-02, 2.8947e-01, 6.1742e-02,
           6.7067e-01, 1.5386e-01, 3.4892e-01, 6.3688e-02, 1.2364e-02,
           1.3409e-01, 5.2426e-01, 6.1800e-01],
          [6.1178e-01, 5.9954e-02, 7.2699e-01, 6.9986e-02, 4.6896e-02,
           2.7759e-01, 9.5121e-01, 4.8335e-01, 9.2043e-02, 7.8694e-01,
           7.3940e-01, 5.2343e-01, 4.1863e-01, 4.999

In [33]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2,0,1)

chw_tensor.shape, chw_tensor

(torch.Size([3, 640, 480]),
 tensor([[[0.3272, 0.8388, 0.7678,  ..., 0.3372, 0.9903, 0.8517],
          [0.1885, 0.3203, 0.6962,  ..., 0.2748, 0.1053, 0.9486],
          [0.9950, 0.5017, 0.0538,  ..., 0.3946, 0.4399, 0.0904],
          ...,
          [0.0819, 0.4257, 0.2502,  ..., 0.8194, 0.0893, 0.4667],
          [0.9710, 0.8011, 0.4074,  ..., 0.4170, 0.4572, 0.6385],
          [0.0092, 0.8622, 0.8428,  ..., 0.3481, 0.7105, 0.8741]],
 
         [[0.1333, 0.6579, 0.9440,  ..., 0.0461, 0.7862, 0.6742],
          [0.8987, 0.9099, 0.1618,  ..., 0.5137, 0.9693, 0.6779],
          [0.3237, 0.8547, 0.6998,  ..., 0.3692, 0.3458, 0.9439],
          ...,
          [0.4910, 0.5490, 0.2990,  ..., 0.9733, 0.8621, 0.9368],
          [0.7908, 0.1682, 0.4526,  ..., 0.1719, 0.1035, 0.2990],
          [0.0982, 0.8147, 0.6084,  ..., 0.8028, 0.3642, 0.5594]],
 
         [[0.5175, 0.1408, 0.3937,  ..., 0.9186, 0.0057, 0.8323],
          [0.5941, 0.7825, 0.8868,  ..., 0.3665, 0.0336, 0.0267],
          [0